-- ART-012E-3 - Discogs enrichment proposals read-only preview
-- Adds a persistent proposal table for Discogs enrichment candidates.
-- This migration does not apply proposals to local artist fields.

CREATE TABLE IF NOT EXISTS public.artist_enrichment_proposals (
  proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_key INTEGER NOT NULL REFERENCES public.artist(ar_artist_key) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'discogs',
  source_external_id TEXT,
  source_reference_id BIGINT REFERENCES public.artist_external_reference(reference_id) ON DELETE SET NULL,
  proposal_type TEXT NOT NULL,
  target_table TEXT NOT NULL DEFAULT 'artist',
  target_field TEXT NOT NULL,
  local_value TEXT,
  proposed_value TEXT,
  proposed_value_normalized TEXT,
  proposed_value_json JSONB,
  extraction_method TEXT NOT NULL DEFAULT 'structured',
  extraction_confidence TEXT NOT NULL DEFAULT 'medium',
  extraction_context TEXT,
  status TEXT NOT NULL DEFAULT 'available',
  conflict_type TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ,
  notes TEXT,
  CONSTRAINT artist_enrichment_proposals_status_chk
    CHECK (status IN ('available', 'conflict', 'existing', 'ignored', 'review_later', 'not_applicable', 'applied', 'error')),
  CONSTRAINT artist_enrichment_proposals_confidence_chk
    CHECK (extraction_confidence IN ('high', 'medium', 'low')),
  CONSTRAINT artist_enrichment_proposals_method_chk
    CHECK (extraction_method IN ('structured', 'profile_text_regex', 'profile_text_heuristic', 'image_metadata', 'discogs_cache', 'manual')),
  CONSTRAINT artist_enrichment_proposals_source_chk
    CHECK (lower(source) IN ('discogs', 'musicbrainz', 'wikidata', 'wikipedia', 'manual'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_artist_enrichment_proposals_dedupe
ON public.artist_enrichment_proposals (
  artist_key,
  lower(source),
  COALESCE(source_external_id, ''),
  proposal_type,
  target_table,
  target_field,
  COALESCE(proposed_value_normalized, proposed_value, '')
);

CREATE INDEX IF NOT EXISTS idx_artist_enrichment_proposals_artist_status
ON public.artist_enrichment_proposals (artist_key, status, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_artist_enrichment_proposals_source_target
ON public.artist_enrichment_proposals (lower(source), target_table, target_field);

COMMENT ON TABLE public.artist_enrichment_proposals IS 'ART-012E-3: read-only enrichment proposals from external sources such as Discogs. Values are not applied automatically.';
COMMENT ON COLUMN public.artist_enrichment_proposals.extraction_context IS 'Short source snippet/context used to explain profile_text_regex or profile_text_heuristic proposals.';
COMMENT ON COLUMN public.artist_enrichment_proposals.extraction_confidence IS 'high/medium/low confidence indicator for user review; not an automatic apply decision.';
