BEGIN;
DO $$ BEGIN
 IF to_regclass('public.musician_in_band') IS NULL THEN
   RAISE EXCEPTION '[ART-013B-1] BLOCKER: public.musician_in_band ontbreekt.';
 END IF;
 IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='musician_in_band' AND column_name='mb_musician_key') THEN
   RAISE EXCEPTION '[ART-013B-1] BLOCKER: bestaande musician-kolom mb_musician_key ontbreekt.';
 END IF;
 IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='musician_in_band' AND column_name='mb_artist_key') THEN
   RAISE EXCEPTION '[ART-013B-1] BLOCKER: bestaande band-kolom mb_artist_key ontbreekt.';
 END IF;
END $$;

-- Het legacy schema bevat geen technische sleutel. Voeg een stabiele interne sleutel
-- toe voor API CRUD, optimistic locking en latere bron/proposal-koppelingen.
ALTER TABLE public.musician_in_band
 ADD COLUMN IF NOT EXISTS mb_musician_band_key bigint GENERATED BY DEFAULT AS IDENTITY,
 ADD COLUMN IF NOT EXISTS mb_role text,
 ADD COLUMN IF NOT EXISTS mb_date_from date,
 ADD COLUMN IF NOT EXISTS mb_date_to date,
 ADD COLUMN IF NOT EXISTS mb_date_from_precision text NOT NULL DEFAULT 'unknown',
 ADD COLUMN IF NOT EXISTS mb_date_to_precision text NOT NULL DEFAULT 'unknown',
 ADD COLUMN IF NOT EXISTS mb_source_type text NOT NULL DEFAULT 'manual',
 ADD COLUMN IF NOT EXISTS mb_source_reference text,
 ADD COLUMN IF NOT EXISTS mb_source_url text,
 ADD COLUMN IF NOT EXISTS mb_notes text,
 ADD COLUMN IF NOT EXISTS mb_created_at timestamptz NOT NULL DEFAULT now(),
 ADD COLUMN IF NOT EXISTS mb_updated_at timestamptz NOT NULL DEFAULT now();

-- Een bestaande tabel kan al een andere primaire sleutel hebben. Daarom wordt de
-- nieuwe technische sleutel uniek gemaakt zonder de bestaande PK te vervangen.
CREATE UNIQUE INDEX IF NOT EXISTS uq_musician_in_band_relation_key
 ON public.musician_in_band(mb_musician_band_key);

DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ck_musician_in_band_period') THEN ALTER TABLE public.musician_in_band ADD CONSTRAINT ck_musician_in_band_period CHECK (mb_date_from IS NULL OR mb_date_to IS NULL OR mb_date_to >= mb_date_from); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ck_musician_in_band_from_precision') THEN ALTER TABLE public.musician_in_band ADD CONSTRAINT ck_musician_in_band_from_precision CHECK (mb_date_from_precision IN ('day','month','year','unknown')); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ck_musician_in_band_to_precision') THEN ALTER TABLE public.musician_in_band ADD CONSTRAINT ck_musician_in_band_to_precision CHECK (mb_date_to_precision IN ('day','month','year','unknown')); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ck_musician_in_band_source_type') THEN ALTER TABLE public.musician_in_band ADD CONSTRAINT ck_musician_in_band_source_type CHECK (mb_source_type IN ('manual','book','website','liner_notes','other')); END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_musician_in_band_artist_period ON public.musician_in_band(mb_artist_key,mb_date_to,mb_date_from);
CREATE INDEX IF NOT EXISTS idx_musician_in_band_musician_period ON public.musician_in_band(mb_musician_key,mb_date_to,mb_date_from);
COMMIT;
