-- ART-012D-4 — Persistente Discogs aliases/name variations reviewqueue
-- Stores Discogs artist names, aliases, real names and name variations as reviewable proposals.

CREATE TABLE IF NOT EXISTS public.artist_name_proposals (
  proposal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_key integer NOT NULL REFERENCES public.artist(ar_artist_key) ON DELETE CASCADE,
  source text NOT NULL DEFAULT 'discogs',
  source_external_id text NOT NULL DEFAULT '',
  source_reference_id bigint REFERENCES public.artist_external_reference(reference_id) ON DELETE SET NULL,
  proposal_name citext NOT NULL,
  normalized_name text NOT NULL,
  proposal_type text NOT NULL,
  source_label text NOT NULL,
  status text NOT NULL DEFAULT 'new',
  conflict_type text,
  conflict_artist_key integer REFERENCES public.artist(ar_artist_key) ON DELETE SET NULL,
  conflict_artist_name citext,
  reason text,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  applied_at timestamp with time zone,
  ignored_at timestamp with time zone,
  notes text,
  CONSTRAINT artist_name_proposals_source_chk CHECK (lower(source) IN ('discogs', 'musicbrainz', 'wikidata', 'wikipedia', 'manual')),
  CONSTRAINT artist_name_proposals_status_chk CHECK (status IN ('new', 'added', 'ignored', 'conflict', 'review_later', 'existing')),
  CONSTRAINT artist_name_proposals_name_not_blank CHECK (trim(proposal_name::text) <> ''),
  CONSTRAINT artist_name_proposals_normalized_not_blank CHECK (trim(normalized_name) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_artist_name_proposals_dedupe
  ON public.artist_name_proposals (artist_key, source, source_external_id, proposal_type, normalized_name);

CREATE INDEX IF NOT EXISTS idx_artist_name_proposals_artist_status
  ON public.artist_name_proposals (artist_key, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_artist_name_proposals_reviewqueue
  ON public.artist_name_proposals (status, updated_at DESC);
