-- ART-015C design migration proposal for artist merge execution.
-- This SQL is a proposal/starter migration and must be reviewed before production use.
-- PostgreSQL / musicdb / Artiesten-app

BEGIN;

ALTER TABLE public.artist
  ADD COLUMN IF NOT EXISTS ar_merged_into_artist_key integer,
  ADD COLUMN IF NOT EXISTS ar_merged_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS ar_merge_note text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'artist_merged_into_artist_key_fkey'
  ) THEN
    ALTER TABLE public.artist
      ADD CONSTRAINT artist_merged_into_artist_key_fkey
      FOREIGN KEY (ar_merged_into_artist_key)
      REFERENCES public.artist(ar_artist_key);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.artist_merge_history (
  merge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  redundant_artist_key integer NOT NULL,
  replacement_artist_key integer NOT NULL,
  redundant_artist_name public.citext NOT NULL,
  replacement_artist_name public.citext NOT NULL,
  merge_reason text,
  performed_by text DEFAULT 'system' NOT NULL,
  performed_at timestamp with time zone DEFAULT now() NOT NULL,
  affected_counts jsonb DEFAULT '{}'::jsonb NOT NULL,
  conflict_summary jsonb DEFAULT '{}'::jsonb NOT NULL,
  notification_status jsonb DEFAULT '{}'::jsonb NOT NULL,
  status text DEFAULT 'completed' NOT NULL,
  CONSTRAINT artist_merge_history_status_check CHECK (status IN ('completed', 'failed', 'rolled_back')),
  CONSTRAINT artist_merge_history_distinct_artists_check CHECK (redundant_artist_key <> replacement_artist_key)
);

CREATE INDEX IF NOT EXISTS idx_artist_merge_history_redundant_artist_key
  ON public.artist_merge_history (redundant_artist_key);

CREATE INDEX IF NOT EXISTS idx_artist_merge_history_replacement_artist_key
  ON public.artist_merge_history (replacement_artist_key);

CREATE INDEX IF NOT EXISTS idx_artist_merge_history_performed_at
  ON public.artist_merge_history (performed_at DESC);

COMMENT ON COLUMN public.artist.ar_merged_into_artist_key IS 'ART-015C: when an artist is merged, points to the canonical replacement artist.';
COMMENT ON COLUMN public.artist.ar_merged_at IS 'ART-015C: timestamp when this artist was merged into another artist.';
COMMENT ON COLUMN public.artist.ar_merge_note IS 'ART-015C: optional note/reason for artist merge.';
COMMENT ON TABLE public.artist_merge_history IS 'ART-015C: audit/history table for artist merge operations.';

COMMIT;

-- Optional FK-hardening after orphan checks. Keep NOT VALID until data is checked/cleaned.
-- ALTER TABLE public.hitlijsten
--   ADD CONSTRAINT hitlijsten_ar_artist_key_fkey
--   FOREIGN KEY (ar_artist_key)
--   REFERENCES public.artist(ar_artist_key)
--   NOT VALID;
--
-- ALTER TABLE public.staging_hitlijsten
--   ADD CONSTRAINT staging_hitlijsten_hl_artist_key_fkey
--   FOREIGN KEY (hl_artist_key)
--   REFERENCES public.artist(ar_artist_key)
--   NOT VALID;
--
-- ALTER TABLE public.import_scan_items
--   ADD CONSTRAINT import_scan_items_fd_artist_key_fkey
--   FOREIGN KEY (fd_artist_key)
--   REFERENCES public.artist(ar_artist_key)
--   NOT VALID;
