import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
test('ART-013A-3 standalone musician backend is wired',()=>{for(const p of ['models/musicianModel.js','services/musicianService.js','controllers/musicianController.js','routes/musicianRoutes.js'])assert.ok(fs.existsSync(p));const r=read('routes/indexRoutes.js');assert.match(r,/\/musicians/);});
test('ART-013A-3 person artist create is transactional with musician',()=>{const c=read('controllers/artistController.js');const s=read('services/artistMusicianLinkService.js');assert.match(c,/createArtistWithMusician/);assert.match(s,/BEGIN/);assert.match(s,/ar_artist_type==='person'/);assert.match(s,/Musician\.create/);});
test('ART-013A-3 supports link unlink and promote',()=>{const s=read('services/artistMusicianLinkService.js');assert.match(s,/async function link/);assert.match(s,/async function unlink/);assert.match(s,/async function promote/);assert.match(s,/MUSICIAN_ALREADY_LINKED/);});
test('ART-013A-3 create-member makes musician and membership atomically',()=>{const s=read('services/musicianInBandService.js');const r=read('routes/musicianInBandRoutes.js');assert.match(r,/create-member/);assert.match(s,/createMember/);assert.match(s,/Musician\.create/);assert.match(s,/INSERT INTO public\.musician_in_band/);assert.match(s,/ROLLBACK/);});
test('ART-013A-3 UI offers new standalone band member',()=>{const ui=read('client/src/features/musician-in-band/MusicianInBandFormModal.jsx');assert.match(ui,/Nieuw bandlid/);assert.match(ui,/geen artist-record aangemaakt/);assert.match(ui,/createMember/);});
test('ART-013A-3 Docker migration scripts use central env',()=>{for(const p of ['scripts/art013a3-preflight.sh','scripts/db-migrate-art013a3-docker.sh','scripts/art013a3-verify.sh','scripts/db-test-art013a3-docker.sh'])assert.ok(fs.existsSync(p));const h=read('scripts/lib/art013a3-db.sh');assert.match(h,/ARTIST_DB_CONTAINER/);assert.match(h,/ARTIST_DB_NAME/);assert.match(h,/ARTIST_DB_USER/);});
test('ART-013A-3 migration keeps nullable artist link and partial unique index',()=>{const sql=read('scripts/sql/20260712_art013a3_artist_musician_asymmetric_model.sql');assert.match(sql,/ALTER COLUMN ar_artist_key DROP NOT NULL/);assert.match(sql,/WHERE ar_artist_key IS NOT NULL/);assert.match(sql,/fn_artist_sync_to_musician/);});
