import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
test("ART-013B-1 backend is modular and routed",()=>{const routes=read("routes/musicianInBandRoutes.js");assert.match(routes,/router\.post\("\/"/);assert.match(routes,/router\.put/);assert.match(routes,/router\.delete/);assert.match(read("routes/indexRoutes.js"),/musician-in-band/)});
test("migration extends existing musician_in_band without replacement",()=>{const sql=read("scripts/sql/20260712_art013b1_musician_in_band_manual_management.sql");assert.match(sql,/ALTER TABLE public\.musician_in_band/);assert.match(sql,/mb_role/);assert.doesNotMatch(sql,/DROP TABLE/)});
test("service protects duplicate overlap and stale updates",()=>{const model=read("models/musicianInBandModel.js");assert.match(model,/MUSICIAN_IN_BAND_DUPLICATE/);assert.match(model,/MUSICIAN_IN_BAND_OVERLAP/);assert.match(model,/STALE_MUSICIAN_IN_BAND/);assert.match(model,/BEGIN/);assert.match(model,/ROLLBACK/)});
test("frontend integrates panel in artist relation insight",()=>{const page=read("client/src/components/ArtistPageContent.jsx");assert.match(page,/BandMembershipPanel/);const panel=read("client/src/features/musician-in-band/BandMembershipPanel.jsx");assert.match(panel,/Bandleden/);assert.match(panel,/Bands \/ groepen/);assert.match(panel,/Bandlid toevoegen/)});
test("external providers remain out of scope",()=>{const all=read("client/src/features/musician-in-band/BandMembershipPanel.jsx")+read("services/musicianInBandService.js");assert.doesNotMatch(all,/DiscogsProvider|MusicBrainzProvider|WikidataProvider/)});
test("preflight migration verify and documentation exist",()=>{for(const p of ["scripts/art013b1-preflight.sh","scripts/db-migrate-art013b1-docker.sh","scripts/art013b1-verify.sh","docs/ART_013B_1_Musician_In_Band_Handmatig_Relatiebeheer_Functioneel_Technisch_Ontwerp.md","docs/ART_013B_1_Testcases_en_Runbook.md"])assert.equal(fs.existsSync(new URL(`../${p}`,import.meta.url)),true)});

test("ART-013B-1 database scripts load the existing project .env contract",()=>{
  const helper=read("scripts/lib/art013b1-db.sh");
  assert.match(helper,/ART013B1_ENV_FILE=.*\.env/);
  assert.match(helper,/source \"\$\{ART013B1_ENV_FILE\}\"/);
  assert.match(helper,/ARTIST_DB_CONTAINER/);
  assert.match(helper,/ARTIST_DB_USER/);
  assert.match(helper,/ARTIST_DB_NAME/);
  assert.doesNotMatch(helper,/POSTGRES_CONTAINER|POSTGRES_DB|POSTGRES_USER/);
  const testScript=read("scripts/db-test-art013b1-docker.sh");
  assert.match(testScript,/art013b1_load_env/);
  assert.match(testScript,/ARTIST_DB_TEST_ALLOWED/);
});

test("Fix-2 accepts the legacy schema and adds a technical relation key",()=>{
  const preflight=read("scripts/sql/20260712_art013b1_preflight.sql");
  const migration=read("scripts/sql/20260712_art013b1_musician_in_band_manual_management.sql");
  const verify=read("scripts/sql/20260712_art013b1_verify.sql");
  assert.match(preflight,/musician foreign-keykolom: mb_musician_key/);
  assert.match(preflight,/band foreign-keykolom: mb_artist_key/);
  assert.match(preflight,/wordt door de migratie toegevoegd/);
  assert.doesNotMatch(preflight,/verwacht mb_musician_band_key, mb_musician_key en mb_artist_key/);
  assert.match(migration,/ADD COLUMN IF NOT EXISTS mb_musician_band_key bigint GENERATED BY DEFAULT AS IDENTITY/);
  assert.match(migration,/CREATE UNIQUE INDEX IF NOT EXISTS uq_musician_in_band_relation_key/);
  assert.doesNotMatch(migration,/BLOCKER: kolom mb_musician_band_key ontbreekt/);
  assert.match(verify,/unieke technische relationsleutel actief/);
});
