const {pool}=require('../config/db');
const Musician=require('../models/musicianModel');

function personOnly(artist){if(!artist||artist.ar_artist_type!=='person'){const e=new Error('Alleen een persoonsartist kan aan een musician worden gekoppeld.');e.code='ARTIST_MUSICIAN_PERSON_REQUIRED';e.statusCode=409;throw e;}}
function musicianDataFromArtist(a){return{name:a.ar_artist_name,dateOfBirth:a.ar_artist_dateofbirth,passingDate:a.ar_artist_passing,websiteUrl:a.ar_website_url,notes:null,artistKey:a.ar_artist_key};}

async function createArtistWithMusician(payload,{musicianKey=null}={}){const client=await pool.connect();try{await client.query('BEGIN');const ar=(await client.query(`INSERT INTO public.artist (ar_artist_name,ar_artist_dateofbirth,ar_artist_passing,ar_website_url,ar_artist_notes,ar_artist_type) VALUES($1,$2::date,$3::date,$4,$5,$6) RETURNING ar_artist_key,ar_artist_name,ar_artist_dateofbirth::text,ar_artist_passing::text,ar_website_url,ar_artist_notes,ar_artist_type`,[payload.ar_artist_name,payload.ar_artist_dateofbirth,payload.ar_artist_passing,payload.ar_website_url,payload.ar_artist_notes,payload.ar_artist_type])).rows[0];
 if(ar.ar_artist_type==='person'){if(musicianKey){const m=await Musician.getById(musicianKey,client);if(!m){const e=new Error('Musician niet gevonden.');e.code='MUSICIAN_NOT_FOUND';e.statusCode=404;throw e;}if(m.artist_key){const e=new Error('Musician is al aan een artist gekoppeld.');e.code='MUSICIAN_ALREADY_LINKED';e.statusCode=409;throw e;}await client.query(`UPDATE public.musician SET ar_artist_key=$1,mu_musician_name=$2,mu_musician_dateofbirth=$3::date,mu_musician_passing=$4::date,mu_website_url=$5 WHERE mu_musician_key=$6`,[ar.ar_artist_key,ar.ar_artist_name,ar.ar_artist_dateofbirth,ar.ar_artist_passing,ar.ar_website_url,musicianKey]);}else await Musician.create(musicianDataFromArtist(ar),client);}
 await client.query('COMMIT');return ar;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

async function link(artistKey,musicianKey){const client=await pool.connect();try{await client.query('BEGIN');const ar=(await client.query(`SELECT ar_artist_key,ar_artist_name,ar_artist_dateofbirth::text,ar_artist_passing::text,ar_website_url,ar_artist_type FROM public.artist WHERE ar_artist_key=$1 FOR UPDATE`,[artistKey])).rows[0];personOnly(ar);if(await Musician.findForArtist(artistKey,client)){const e=new Error('Artist heeft al een musician.');e.code='ARTIST_ALREADY_HAS_MUSICIAN';e.statusCode=409;throw e;}const m=await Musician.getById(musicianKey,client);if(!m){const e=new Error('Musician niet gevonden.');e.code='MUSICIAN_NOT_FOUND';e.statusCode=404;throw e;}if(m.artist_key){const e=new Error('Musician is al gekoppeld.');e.code='MUSICIAN_ALREADY_LINKED';e.statusCode=409;throw e;}await client.query(`UPDATE public.musician SET ar_artist_key=$1,mu_musician_name=$2,mu_musician_dateofbirth=$3::date,mu_musician_passing=$4::date,mu_website_url=$5 WHERE mu_musician_key=$6`,[artistKey,ar.ar_artist_name,ar.ar_artist_dateofbirth,ar.ar_artist_passing,ar.ar_website_url,musicianKey]);await client.query('COMMIT');return Musician.getById(musicianKey);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

async function unlink(artistKey){const client=await pool.connect();try{await client.query('BEGIN');const ar=(await client.query('SELECT ar_artist_type FROM public.artist WHERE ar_artist_key=$1 FOR UPDATE',[artistKey])).rows[0];personOnly(ar);const r=await client.query('UPDATE public.musician SET ar_artist_key=NULL WHERE ar_artist_key=$1 RETURNING mu_musician_key',[artistKey]);await client.query('COMMIT');return r.rows[0]||null;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

async function promote(musicianKey,artistPayload){const client=await pool.connect();try{await client.query('BEGIN');const m=await Musician.getById(musicianKey,client);if(!m){const e=new Error('Musician niet gevonden.');e.code='MUSICIAN_NOT_FOUND';e.statusCode=404;throw e;}if(m.artist_key){const e=new Error('Musician is al gekoppeld.');e.code='MUSICIAN_ALREADY_LINKED';e.statusCode=409;throw e;}const ar=(await client.query(`INSERT INTO public.artist(ar_artist_name,ar_artist_dateofbirth,ar_artist_passing,ar_website_url,ar_artist_notes,ar_artist_type) VALUES($1,$2::date,$3::date,$4,$5,'person') RETURNING ar_artist_key,ar_artist_name,ar_artist_type`,[artistPayload.ar_artist_name||m.musician_name,artistPayload.ar_artist_dateofbirth||m.date_of_birth,artistPayload.ar_artist_passing||m.passing_date,artistPayload.ar_website_url||m.website_url,artistPayload.ar_artist_notes||null])).rows[0];await client.query('UPDATE public.musician SET ar_artist_key=$1 WHERE mu_musician_key=$2',[ar.ar_artist_key,musicianKey]);await client.query('COMMIT');return{artist:ar,musician:await Musician.getById(musicianKey)};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
module.exports={createArtistWithMusician,link,unlink,promote};
