import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Alert,Badge,Button,Form,Modal,Table} from 'react-bootstrap';
import {musicianInBandProposalApi as api} from './api.js';
function statusVariant(status){return status==='accepted'?'success':status==='conflict'?'danger':status==='ignored'?'secondary':status==='review_later'?'warning':'primary'}
function needsArtistCorrection(row){return ['artist_type_missing','ambiguous'].includes(row.match_status)}
function canCreateStandalone(row){return ['artist_type_conflict'].includes(row.match_status)}
function matchLabel(row){if(row.matched_musician_name)return row.matched_musician_name;if(row.matched_artist_name)return `${row.matched_artist_name} (${row.matched_artist_type||'unknown'})`;return 'Nieuwe standalone musician'}
export default function DiscogsBandMemberProposalQueue({artist,show,onHide,onChanged}){
 const [items,setItems]=useState([]),[counts,setCounts]=useState([]),[error,setError]=useState(''),[info,setInfo]=useState(''),[loading,setLoading]=useState(false);
 const [status,setStatus]=useState(''),[q,setQ]=useState('');
 const tableWrapRef=useRef(null),pendingAnchorRef=useRef(null);
 const countMap=useMemo(()=>Object.fromEntries((counts||[]).map(x=>[x.proposal_status,x.count])),[counts]);
 async function load(){if(!show||!artist?.ar_artist_key)return;setLoading(true);setError('');try{const d=await api.list(artist.ar_artist_key,{status,q});setItems(d.items||[]);setCounts(d.counts||[])}catch(e){setError(e.payload?.code==='ART013B2_MIGRATION_REQUIRED'?'De database-uitbreiding voor Discogs-bandledenvoorstellen ontbreekt. Voer eerst npm run db:migrate:art013b2 uit.':e.message)}finally{setLoading(false)}}
 async function rematch({silent=false}={}){if(!show||!artist?.ar_artist_key)return;setLoading(true);setError('');try{const d=await api.rematch(artist.ar_artist_key);const sm=d.summary||{};if(!silent)setInfo(`Lokale matches vernieuwd: ${sm.processed||0} voorstellen gecontroleerd.`);await load()}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(show&&artist?.ar_artist_key)rematch({silent:true})},[show,artist?.ar_artist_key]);
 useEffect(()=>{if(show)load()},[status]);
 useEffect(()=>{const anchor=pendingAnchorRef.current;if(!anchor||loading)return;const wrap=tableWrapRef.current;if(!wrap)return;requestAnimationFrame(()=>{wrap.scrollTop=anchor.scrollTop;const next=wrap.querySelector(`[data-proposal-key=\"${anchor.proposalKey}\"]`)||wrap.querySelector('[data-proposal-row] button:not(:disabled)');if(next?.focus)next.focus({preventScroll:true});pendingAnchorRef.current=null;});},[items,loading]);
 async function generate(){setLoading(true);setError('');try{const d=await api.generate(artist.ar_artist_key);const s=d.summary||{};setInfo(`Discogs verwerkt: ${s.processed||0}, nieuw: ${s.inserted||0}, bijgewerkt: ${s.updated||0}.`);await load()}catch(e){setError(e.payload?.code==='ART013B2_MIGRATION_REQUIRED'?'De database-uitbreiding voor Discogs-bandledenvoorstellen ontbreekt. Voer eerst npm run db:migrate:art013b2 uit.':e.message)}finally{setLoading(false)}}
 async function mutate(row,action){setError('');const wrap=tableWrapRef.current;pendingAnchorRef.current={proposalKey:row.proposal_key,scrollTop:wrap?.scrollTop||0,viewportTop:wrap?.getBoundingClientRect?.().top||0};try{if(action==='accept')await api.accept(row.proposal_key,{expectedUpdatedAt:row.updated_at});else if(action==='create_standalone')await api.accept(row.proposal_key,{expectedUpdatedAt:row.updated_at,createStandalone:true});else await api.setStatus(row.proposal_key,action,row.updated_at);await load();onChanged?.()}catch(e){setError(e.message)}}
 return <Modal show={show} onHide={onHide} size="xl" centered><Modal.Header closeButton><Modal.Title>Discogs bandledenvoorstellen — {artist?.ar_artist_name}</Modal.Title></Modal.Header><Modal.Body>
  <div className="d-flex flex-wrap gap-2 justify-content-between mb-3"><div className="d-flex gap-2"><Button onClick={generate} disabled={loading}>Discogs opnieuw ophalen</Button><Button variant="outline-primary" onClick={()=>rematch()} disabled={loading}>Lokale matches vernieuwen</Button><Button variant="outline-secondary" onClick={load}>Ververs</Button></div><div className="d-flex gap-2"><Form.Select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter voorstelstatus"><option value="">Alle statussen</option><option value="new">Nieuw ({countMap.new||0})</option><option value="review_later">Later ({countMap.review_later||0})</option><option value="ignored">Genegeerd ({countMap.ignored||0})</option><option value="accepted">Geaccepteerd ({countMap.accepted||0})</option><option value="conflict">Conflict ({countMap.conflict||0})</option></Form.Select><Form.Control value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}} placeholder="Zoek naam"/></div></div>
  {error?<Alert variant="danger">{error}</Alert>:null}{info?<Alert variant="success" dismissible onClose={()=>setInfo('')}>{info}</Alert>:null}
  {loading?<div className="text-muted">Laden...</div>:<div ref={tableWrapRef} className="discogs-member-proposal-table-wrap" data-scroll-container="discogs-member-proposals"><Table responsive size="sm" className="discogs-member-proposal-table"><thead><tr><th>Discogs-naam</th><th>Lokale match</th><th>Classificatie</th><th>Status</th><th className="discogs-member-proposal-actions-heading">Acties</th></tr></thead><tbody>{items.length?items.map(r=><tr key={r.proposal_key} data-proposal-row data-proposal-key={r.proposal_key}><td><div>{r.proposed_person_name}</div>{r.source_url?<a href={r.source_url} target="_blank" rel="noreferrer">Open Discogs</a>:null}</td><td><div>{matchLabel(r)}</div>{r.proposed_artist_key?<div className="small text-muted">Artist key: {r.proposed_artist_key}</div>:null}</td><td className="discogs-member-proposal-classification"><Badge bg="light" text="dark">{r.match_status}</Badge>{r.conflict_reason?<div className="small text-danger discogs-member-proposal-message" title={r.conflict_reason}>{r.conflict_reason}</div>:null}</td><td><Badge bg={statusVariant(r.proposal_status)}>{r.proposal_status}</Badge></td><td className="discogs-member-proposal-actions"><div className="discogs-member-proposal-actionbar">{r.proposal_status!=='accepted'&&!needsArtistCorrection(r)&&!canCreateStandalone(r)?<Button size="sm" onClick={()=>mutate(r,'accept')}>Accepteer</Button>:null}{r.proposal_status!=='accepted'&&canCreateStandalone(r)?<Button size="sm" onClick={()=>mutate(r,'create_standalone')}>Aanmaken als musician</Button>:null}{needsArtistCorrection(r)?<Button size="sm" variant="outline-danger" disabled title="Controleer eerst de lokale kandidaten; lokale matching wordt bij openen automatisch vernieuwd">Controle nodig</Button>:null}{r.proposal_status!=='review_later'?<Button size="sm" variant="outline-warning" onClick={()=>mutate(r,'review_later')}>Later</Button>:null}{r.proposal_status!=='ignored'?<Button size="sm" variant="outline-secondary" onClick={()=>mutate(r,'ignored')}>Voorstel negeren</Button>:null}{['ignored','review_later','conflict'].includes(r.proposal_status)?<Button size="sm" variant="outline-primary" onClick={()=>mutate(r,'new')}>Heropen</Button>:null}</div></td></tr>):<tr><td colSpan="5" className="text-muted">Nog geen Discogs-bandledenvoorstellen.</td></tr>}</tbody></Table></div>}
 </Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Sluiten</Button></Modal.Footer></Modal>
}
