-- ART-012E-4 - Discogs enrichment proposal apply/review actions
-- Adds external profile storage and review/apply metadata for enrichment proposals.

ALTER TABLE public.artist_enrichment_proposals
  ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS applied_by TEXT,
  ADD COLUMN IF NOT EXISTS ignored_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ignored_by TEXT,
  ADD COLUMN IF NOT EXISTS reviewed_by TEXT;

CREATE TABLE IF NOT EXISTS public.artist_external_profile (
  external_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_key INTEGER NOT NULL REFERENCES public.artist(ar_artist_key) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'discogs',
  source_external_id TEXT,
  source_reference_id BIGINT REFERENCES public.artist_external_reference(reference_id) ON DELETE SET NULL,
  profile_text TEXT NOT NULL,
  profile_url TEXT,
  is_primary BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'active',
  fetched_at TIMESTAMPTZ,
  stored_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  raw_data_json JSONB,
  CONSTRAINT artist_external_profile_source_chk CHECK (lower(source) IN ('discogs', 'musicbrainz', 'wikidata', 'wikipedia', 'manual')),
  CONSTRAINT artist_external_profile_status_chk CHECK (status IN ('active', 'ignored', 'stale', 'error'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_artist_external_profile_source
ON public.artist_external_profile (
  artist_key,
  lower(source),
  COALESCE(source_external_id, '')
);

CREATE INDEX IF NOT EXISTS idx_artist_external_profile_artist
ON public.artist_external_profile (artist_key, status, stored_at DESC);

COMMENT ON TABLE public.artist_external_profile IS 'ART-012E-4: external artist profile text such as Discogs profile text. Kept separate from local artist notes.';
COMMENT ON COLUMN public.artist_enrichment_proposals.applied_at IS 'ART-012E-4: timestamp when a proposal was explicitly applied by the user.';
COMMENT ON COLUMN public.artist_enrichment_proposals.ignored_at IS 'ART-012E-4: timestamp when a proposal was explicitly ignored by the user.';
